# 90_export_overleaf.R — exporta tabelas (booktabs), figuras (PDF+PNG) e números citados (\newcommand) para o Overleaf.
# O autor escreve o texto; este script só produz os insumos numéricos. Saída: outputs/overleaf/.
# Nenhum nome de parte, advogado ou magistrado é exportado; relatores só em nível de órgão/turma.
suppressPackageStartupMessages({ library(dplyr); library(readr); library(ggplot2); library(stringi) })
root <- Sys.getenv("STJMD_ROOT", unset = ".")
od <- file.path(root, "outputs/overleaf"); for (d in c("tables", "figures")) dir.create(file.path(od, d), showWarnings = FALSE, recursive = TRUE)

tex_escape <- function(x) stri_replace_all_regex(as.character(x), "([%&_#$])", "\\\\$1")
booktabs <- function(df, file, caption, label, digits = 0) {
  fmt <- function(v) if (is.numeric(v)) formatC(v, format = "f", digits = digits, big.mark = ",") else tex_escape(v)
  body <- apply(df, 1, function(r) paste(r, collapse = " & "))
  body <- apply(as.data.frame(lapply(df, fmt), stringsAsFactors = FALSE), 1, paste, collapse = " & ")
  align <- paste(ifelse(sapply(df, is.numeric), "r", "l"), collapse = "")
  lines <- c("\\begin{table}[htbp]", "\\centering", sprintf("\\caption{%s}", caption), sprintf("\\label{%s}", label),
             sprintf("\\begin{tabular}{%s}", align), "\\toprule", paste(tex_escape(names(df)), collapse = " & "), " \\\\", "\\midrule",
             paste0(body, " \\\\"), "\\bottomrule", "\\end{tabular}", "\\end{table}")
  writeLines(lines, file)
}
num <- list()
addnum <- function(name, value, digits = 0) num[[name]] <<- if (is.numeric(value)) formatC(value, format = "f", digits = digits, big.mark = ",") else as.character(value)

# --- piloto: tabela de matérias candidatas ------------------------------------------------------
ts <- file.path(root, "data/interim/topic_screen.csv")
if (file.exists(ts)) {
  screen <- read_csv(ts, show_col_types = FALSE) |> transmute(Topic = materia, `Docs (moral damages)` = docs_dano_moral,
                                                                `Docs with award value` = docs_com_valor_dm, `Share` = share_docs)
  booktabs(screen, file.path(od, "tables/pilot_topic_screen.tex"), "Candidate topics in the seven-day pilot sample (STJ decisions mentioning moral damages)", "tab:pilot_topics", digits = 3)
}
# --- piloto: distribuição de valores (sem identificação) ----------------------------------------
pa <- file.path(root, "data/interim/pilot_amounts.csv")
if (file.exists(pa)) {
  a <- read_csv(pa, show_col_types = FALSE)
  d <- a |> filter(category %in% c("dano_moral", "moral_material_conjunto"), !in_precedent_quote, unit == "BRL")
  if ("reference_value" %in% names(d)) d <- filter(d, !reference_value)
  addnum("pilotCandidates", nrow(a)); addnum("pilotMoralCandidates", nrow(d)); addnum("pilotMoralDocs", n_distinct(d$doc_id))
  addnum("pilotMoralMedianBRL", median(d$value)); addnum("pilotMoralPNinetyBRL", quantile(d$value, .9))
  g <- ggplot(d, aes(value)) + geom_histogram(bins = 40, fill = "grey30") + scale_x_log10(labels = scales::label_dollar(prefix = "R$ ")) +
    labs(x = "Moral-damages amount (nominal BRL, log scale)", y = "Candidates", title = NULL) + theme_minimal(base_size = 11)
  ggsave(file.path(od, "figures/pilot_value_distribution.pdf"), g, width = 6, height = 3.5)
  ggsave(file.path(od, "figures/pilot_value_distribution.png"), g, width = 6, height = 3.5, dpi = 200)
}
sc <- file.path(root, "data/interim/sample_dm_corpus.rds"); sa <- file.path(root, "data/interim/sample_all_docs.rds")
if (file.exists(sc) && file.exists(sa)) { addnum("pilotDocsTotal", nrow(readRDS(sa))); addnum("pilotDocsMoral", nrow(readRDS(sc))) }
# --- numbers.tex ----------------------------------------------------------------------------------
if (length(num)) writeLines(c("% generated by scripts/90_export_overleaf.R — do not edit by hand",
                              sprintf("\\newcommand{\\%s}{%s}", names(num), unlist(num))), file.path(od, "numbers.tex"))
cat("exportado para", od, ":", length(list.files(od, recursive = TRUE)), "arquivos\n")
